const locations = {
  layer1: [
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer1/dvn1.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer1/s5.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer1/s11.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer1/S16.png",
      altText: "image of Metabnb location",
    },
  ],
  layer2: [
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer2/aise1.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer2/aise2.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer2/druids6.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer2/s1.png",
      altText: "image of Metabnb location",
    },
  ],
  layer3: [
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer3/druids4.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer3/s2.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer3/s8.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer3/s12.png",
      altText: "image of Metabnb location",
    },
  ],
  layer4: [
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer4/s9.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer4/susan3.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer4/susan5.png",
      altText: "image of Metabnb location",
    },
    {
      name: "Desert king",
      price: "1MBT per night",
      distance: "2345km",
      duration: "2weeks",
      stars: 5,
      imgUrl: "layer4/susan8.png",
      altText: "image of Metabnb location",
    },
  ],
}

export default locations;